### ISSUE TITLE
Moving to Python 3.7

### ISSUE THREAD

**Issue by robzajac** [zixuanzh/py-libp2p#88]
Python 3.7 brought [some improvements to asyncio](https://docs.python.org/3/whatsnew/3.7.html#asyncio), but we have waited to make the upgrade to ensure compatibility with py-evm. But it seems py-evm [has upgraded](https://github.com/ethereum/py-evm/blob/master/.circleci/config.yml#L337) - is py-libp2p ready to upgrade as well?

**Comment by zixuanzh** [comment]
If we are using some of the improvements to asyncio in Python 3.7, then we should proceed with the update and not wait. Otherwise, we don't have to do it right away. Regardless, py-libp2p should be ready to upgrade to Python 3.7 at any time.

Maybe @alexh can take a look at this too and evaluate if there are any improvements in asyncio that we can leverage.

**Comment by robzajac** [comment]
Notably there are [performance improvements](https://docs.python.org/3/whatsnew/3.7.html#whatsnew37-asyncio-perf) we could leverage, but in general we should be ready to upgrade to the most recent Python version as soon as possible like you said.

**Comment by pipermerriam** [comment]
I suspect that py-evm will support python 3.6 for a while, **but** trinity which is the component which needs this could easily be only 3.7+ so I'm ok with 3.7 being the baseline development target for this codebase.
